DECLARE 
ans NUMBER := 0;
emp_name copy.ename %type;
cursor curse IS SELECT * FROM COPY;
BEGIN
ans:=45/0;
SELECT ename INTO emp_name FROM copy WHERE mgr=7839;
-- CLOSE curse;
-- INSERT INTO COPY VALUES(7783,'Rathore','INTERN',7839,sysdate,576,null,40);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX then
DBMS_OUTPUT.PUT_LINE('No Duplications Allowed. Primary Key constraint there');
WHEN INVALID_CURSOR then
DBMS_OUTPUT.PUT_LINE('There is something wrong with cursor');
WHEN NO_DATA_FOUND then
DBMS_OUTPUT.PUT_LINE('No DATA FOUND EXCEPTION CAUGHT HERE');
WHEN TOO_MANY_ROWS then
DBMS_OUTPUT.PUT_LINE('TOO MANY ROWS EXCEPTION CAUGHT HERE');
WHEN ZERO_DIVIDE then
DBMS_OUTPUT.PUT_LINE('ZERO DIVIDE ECEPTION CAUGHT HERE.');
WHEN others then
DBMS_OUTPUT.PUT_LINE('error!');
DBMS_OUTPUT.PUT_LINE(TO_CHAR(SQL%ROWCOUNT)||' Affected.');
END;
